Exception: Show error messages body
This fix is because errors coming from lcb would not have any
contextual detail within JavaScript land. This fix changes this to use
Nan's built in NanError.